stages:
  - deploy

deploy_develop:
  stage: deploy
  script:
    - echo "Installing..."
    - npm install
    - echo "Building project in $(pwd)"
    - rm -Rf build/
    - npm run build
    - echo "Project has been compiled"
    - chgrp -R srv /srv/dev.teoconan.fr
    - echo "Deploy finished"
  environment:
    name: develop
    url: https://dev.teoconan.fr