stages:
  - deploy

deploy_develop:
  stage: deploy
  script:
    - echo "Installing..."
    - npm install
    - echo "Building project in $(pwd)"
    - npm run build
    - echo "Project has been compiled"
    - echo "Deploy finished"
  environment:
    name: develop
    url: https://dev.teoconan.fr