stages:
  - deploy

deploy_develop:
  stage: deploy
  script:
    - echo "Installing..."
    - npm install
    - echo "Building project in $(pwd)"
    - npm run build
    - echo "Project has been compiled"
    - mkdir /srv/dev.teoconan.fr.tmp && cp -R ./ /srv/dev.teoconan.fr.tmp/
    - rm -Rf /srv/dev.teoconan.fr && mv /srv/dev.teoconan.fr.tmp /srv/dev.teoconan.fr
    - echo "Deploy finished"
  environment:
    name: develop
    url: https://dev.teoconan.fr